services:
    frontend:
      image: docker.io/busybox
      command: ["/bin/busybox", "httpd", "-f", "-p", "8080"]
      working_dir: /
      environment:
        SECRET_KEY2: aabbcc
        ENV_IS_SET2:
      expose:
        - "8080"
      labels:
        my.label: my_value
      networks:
        - reverseproxy
        - busybox

networks:
  reverseproxy:
    external: true
    name: reverseproxy
  busybox:
