# example config
[[services]]
name = "pgo"
user = "miek"  # under which user to run the podman
repository = "https://github.com/miekg/pgo"
branch = "main"
urls = { "slashdot.org" = 5010 }
ports = [ "5005/5", "1025/5" ]
