[[services]]
name = "caddy"
user = "root"
repository = "https://github.com/miekg/pgo-caddy"
import = "caddy/Caddyfile-import"
ports = [ "443/0", "80/0" ]

[[services]]
name = "pgo"
branch = "main"
user = "miek"
repository = "https://github.com/miekg/pgo"
#registry = "user:pass"
env = [ "SECRET=mysecret" ]
urls = { "slashdot.org" = "pgo:8080" }
ports = [ "8080/5" ]
